# Generated by Django 5.2.5 on 2025-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completion_time",
            new_name="completed_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="in_progress",
        ),
        migrations.AddField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("In progress", "In progress"),
                    ("Completed", "Completed"),
                ],
                default="New",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
