# Generated by Django 5.2.5 on 2025-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_completion_time_task_completed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="state",
            new_name="status",
        ),
    ]
