# Generated by Django 5.2.5 on 2025-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_rename_state_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "In progress"),
                    ("completed", "Completed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
