# Generated by Django 5.2.5 on 2025-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-due_by"]},
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Very important"),
                    ("high", "Important"),
                    ("medium", "Normal"),
                    ("low", "Optional"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
