# Generated by Django 5.2.5 on 2025-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_alter_task_options_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": [models.OrderBy(models.F("due_by"), nulls_last=True)]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="tag",
            new_name="tags",
        ),
    ]
