# Generated by Django 5.2.5 on 2025-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_task_options_rename_tag_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    "priority",
                    models.OrderBy(models.F("due_by"), nulls_last=True),
                ]
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[(0, "critical"), (1, "high"), (2, "medium"), (3, "low")],
                default="medium",
                max_length=20,
            ),
        ),
    ]
