# Generated by Django 5.2.5 on 2025-08-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_task_options_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "critical"), (1, "high"), (2, "medium"), (3, "low")],
                default="2",
            ),
        ),
    ]
