# Generated by Django 5.2.5 on 2025-08-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_alter_task_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
    ]
