# Generated by Django 5.2.5 on 2025-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
