# Generated by Django 5.2.5 on 2025-08-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0011_alter_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
