# Generated by Django 5.2.5 on 2025-08-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0012_alter_task_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": [
                    "priority",
                    models.OrderBy(models.F("due_by"), nulls_last=True),
                    "created_at",
                ]
            },
        ),
    ]
