# Generated by Django 5.2.5 on 2025-08-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0014_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
    ]
