# Generated by Django 5.2.5 on 2025-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0015_alter_comment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tasks", to="board.tag"
            ),
        ),
    ]
