# Generated by Django 5.2.5 on 2025-08-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0016_alter_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "blue"),
                    ("brown", "brown"),
                    ("gray", "gray"),
                    ("green", "green"),
                    ("magenta", "magenta"),
                    ("olive", "olive"),
                    ("orange", "orange"),
                    ("purple", "purple"),
                    ("teal", "teal"),
                    ("turquoise", "turquoise"),
                    ("red", "red"),
                    ("yellow", "yellow"),
                ],
                default="olive",
                max_length=200,
            ),
        ),
    ]
