# Generated by Django 5.2.5 on 2025-08-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0019_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("blue", "blue"),
                    ("brown", "brown"),
                    ("gray", "gray"),
                    ("green", "green"),
                    ("olive", "olive"),
                    ("orange", "orange"),
                    ("pink", "pink"),
                    ("purple", "purple"),
                    ("teal", "teal"),
                    ("turquoise", "turquoise"),
                    ("red", "red"),
                    ("yellow", "yellow"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
